version: "3.9"
services:
  minio:
    image: "quay.io/minio/minio:RELEASE.2023-02-27T18-10-45Z"
    ports:
    - "9000:9000"
    - "9090:9090"
    environment:
    - "MINIO_ROOT_USER=$MINIO_USER"
    - "MINIO_ROOT_PASSWORD=$MINIO_PASSWORD"
    volumes:
    - miniodata:/data
    command: server /data --console-address ":9090"

volumes:
  miniodata: {}